; version.asm
;
; Auto-generated by ZXVersion.exe
; On 02 Nov 2023 at 04:47

    macro BuildNo
                        db "11"
    endm

    define BuildNoValue "11"




    macro CommitHash
                        db "08e6d639e541a775b5642e76b3d77174b539e37d"
    endm

    macro CommitHashShort
                        db "08e6d63"
    endm

    define CommitHashValue "08e6d639e541a775b5642e76b3d77174b539e37d"

    define CommitHashShortValue "08e6d63"

    macro BuildDate
                        db "02 Nov 2023"
    endm

    define BuildDateValue "02 Nov 2023"



    macro BuildTime
                        db "04:47"
    endm

    define BuildTimeValue "04:47"



    macro BuildTimeSecs
                        db "04:47:10"
    endm

    define BuildTimeSecsValue "04:47:10"
