; version.asm
;
; Auto-generated by ZXVersion.exe
; On 13 Oct 2023 at 16:10

    macro BuildNo
                        db "7"
    endm

BuildNoValue            equ "7"



    macro CommitHash
                        db "fed079b2d63090ecf130317e0b492dcd07ef2a1f"
    endm

    macro CommitHashShort
                        db "fed079b"
    endm

    define CommitHashValue "fed079b2d63090ecf130317e0b492dcd07ef2a1f"

    define CommitHashShortValue "fed079b"

    macro BuildDate
                        db "13 Oct 2023"
    endm

    define BuildDateValue "13 Oct 2023"



    macro BuildTime
                        db "16:10"
    endm

    define BuildTimeValue "16:10"



    macro BuildTimeSecs
                        db "16:10:44"
    endm

    define BuildTimeSecsValue "16:10:44"
